29 create transaction history component
ZackHolmberg/COMP4350-Project pull request #110
Opened 2021-03-22 03:39 UTC by madisonfines

Implemented transaction history component on home page. Click component to see transaction history.

Closes #29

2021-03-22 03:40 UTC, madisonfines commented on src/frontend/src/store/index.ts
> +      /* const transactions = [
To be removed, used for testing

2021-03-22 04:02 UTC, ZackHolmberg commented on src/frontend/src/store/index.ts
> +            commit("MUTATION_SET_TRANSACTION_HISTORY", response.data);
Verify this will work with backend implementation when it is up

2021-03-22 04:03 UTC, ZackHolmberg approved these changes
![nice](https://i.pinimg.com/originals/54/2d/89/542d896e247cb245d0c82ac67d885621.gif)

2021-03-23 05:24 UTC, akshaysharma21 requested changes

2021-03-23 05:24 UTC, akshaysharma21 commented on src/frontend/src/store/index.ts
> +        .get("http://localhost//wallet/history?walletId="+ getters.walletId)
Gonna need to update this to the backend route without the payload

2021-03-23 05:26 UTC, abhisachdev17 approved these changes
Just one change, rest looks good

2021-03-23 05:26 UTC, abhisachdev17 commented on src/frontend/src/store/index.ts
> +        .get("http://localhost//wallet/history?walletId="+ getters.walletId)
you will need to change this to `http://localhost/wallet/history/ + getters.walletId`

2021-03-23 05:36 UTC, abhisachdev17 commented on src/frontend/src/store/index.ts
> +        .get("http://localhost//wallet/history?walletId="+ getters.walletId)
This reminded me the walletId doesn't exist anymore. You will need to use getters.umnetId

2021-03-23 17:23 UTC, ZackHolmberg commented on src/frontend/src/store/index.ts
> +        .get("http://localhost//wallet/history/"+ getters.umnetId)
Extra '/` here in `localhost//wallet`, not sure if it actually affects the success of the call or not

2021-03-23 18:29 UTC, akshaysharma21 approved these changes

2021-03-23 21:00 UTC, ZackHolmberg approved these changes

2021-03-23 21:00 UTC, ZackHolmberg commented on src/frontend/src/components/TransactionHistory.vue
> +    }
I think this can just be one-lined as `this.$data.active = !this.$data.active`

2021-03-23 22:02 UTC, merged