Added repo-wide linter
ZackHolmberg/COMP4350-Project pull request #142
Opened 2021-04-05 22:13 UTC by ZackHolmberg

closes #141

2021-04-05 22:21 UTC, ZackHolmberg commented
Generated logs:
[linters_logs.zip](https://github.com/ZackHolmberg/COMP4350-Project/files/6260921/linters_logs.zip)

2021-04-05 22:32 UTC, ZackHolmberg commented on .github/workflows/mega-linter.yml
> +    branches: [master, main]
remove main, add staging

2021-04-05 22:49 UTC, ZackHolmberg commented
![Screen Shot 2021-04-05 at 5 48 41 PM](https://user-images.githubusercontent.com/28747184/113635948-30bd1d80-9637-11eb-8e13-7fc354ed60ec.png) theses auto-fix jobs are supposed to be running but I am not sure why they aren't. Regardless, this PR is only for adding the linter so it's good for review.

2021-04-06 00:34 UTC, abhisachdev17 requested changes
This looks good to me, before merging can you remove the flake8 linter from the python workflow and one concern: Is this going to be failing for every PR we create?

2021-04-06 00:38 UTC, abhisachdev17 commented
Also, do we need to run both flake8 and pylint for python?

2021-04-06 00:39 UTC, madisonfines approved these changes

2021-04-07 03:29 UTC, abhisachdev17 approved these changes
LGTM

2021-04-07 03:37 UTC, merged