19: Initialize front end app and create basic interface
ZackHolmberg/COMP4350-Project pull request #24
Opened 2021-02-12 21:39 UTC by ZackHolmberg

# Summary of Changes:

- Initialized a Vue app for the frontend
- Added a mock login page
- Wrote a couple of reusable components 

# How to test
- You will vue CLI installed on your computer
- Navigate to the app/bisoncoin folder
- Run `npm install` to install dependencies
- Run `npm run serve` to run the app on a local port
- Open the address in the browser

Closes #19

2021-02-12 21:46 UTC, ZackHolmberg commented on src/app/bisoncoin/src/components/Button.vue
> +  border: none;
Can remove this as it is being overwritten

2021-02-12 21:46 UTC, ZackHolmberg commented on src/app/bisoncoin/src/components/Button.vue
> +  background-color: #00a3e050;
Should store all colours and text in separate asset files and then reference them in components and styles

2021-02-12 21:46 UTC, ZackHolmberg commented on src/app/bisoncoin/src/pages/HomePage.vue
> +  @Prop() private msg!: string;
Can remove this, don't need it

2021-02-12 21:46 UTC, ZackHolmberg commented on src/app/bisoncoin/src/pages/HomePage.vue
> +    <h1>{{ msg }}</h1>
Remove use of the prop that we're removing

2021-02-12 21:46 UTC, ZackHolmberg commented on src/app/bisoncoin/src/pages/HomePage.vue
> +<!-- Add "scoped" attribute to limit CSS to this component only -->
Remove comment

2021-02-12 21:46 UTC, ZackHolmberg commented on src/app/bisoncoin/src/pages/LoginPage.vue
> +    <a href="hello">Don't have an account? Create one now!</a>
Updated HREF to say TODO instead. Additionally, move this hardcoded text into a separate file as mentioned prior

2021-02-12 21:46 UTC, ZackHolmberg commented on src/app/bisoncoin/tests/e2e/specs/test.js
> +// https://docs.cypress.io/api/introduction/api.html
Should add a mock E2E test for future reference!

2021-02-12 21:46 UTC, ZackHolmberg commented on src/blockchain/blockchain.py
> +from hashlib import sha256
Remove this file!

2021-02-12 21:47 UTC, ZackHolmberg commented on src/app/bisoncoin/package.json
> +{
Add this file to git ignore!

2021-02-13 00:44 UTC, madisonfines approved these changes

2021-02-13 00:51 UTC, abhisachdev17 requested changes
can you move the folder structure to be frontend > src > .. to separate frontend and backend folders.

2021-02-13 17:05 UTC, ZackHolmberg commented
> can you move the folder structure to be frontend > src > .. to separate frontend and backend folders.

@abhisachdev17 The current folder structure is kind of trying to do this already, with src being src code parent folder, and then next 3 directories are `app` (frontend), `services`(middleware) and `blockchain` (could be called backend). Do you think this is satisfactory or did you have something different in mind?

2021-02-13 21:13 UTC, abhisachdev17 commented
> you

I was thinking of having frontend and backend in the root directory of the project, for separation right from the beginning.

2021-02-15 23:20 UTC, abhisachdev17 approved these changes

2021-02-16 00:37 UTC, merged