Mining Updates
ZackHolmberg/COMP4350-Project pull request #67
Opened 2021-02-23 23:46 UTC by abhisachdev17

## Summary of Changes
- Mining Pool Object which contains a pool of transactions
- One transaction is picked from the pool to be sent for Mining
- The transaction is only sent when the ready_to_mine condition variable with help of send is set.
- The ready_to_mine is set when the miners send back a valid proof of work.
TLDR; lots of OS stuff, let me know if you have any doubts on how things work.

Closes #12

2021-02-23 23:57 UTC, ZackHolmberg requested changes

2021-02-23 23:57 UTC, ZackHolmberg commented on src/backend/services/mining-api/src/MiningPool.py
> +    def start_thread(self):
I may be missing it but I don't see where this gets called. If that's the case, does it need to be called or can we remove it? Should be called in init I'd think

2021-02-23 23:57 UTC, ZackHolmberg commented on src/backend/services/transaction-api/src/routes.py
> +ongoing_proof_for_id = None
Is this supposed to be here?

2021-02-23 23:57 UTC, ZackHolmberg commented on src/backend/services/mining-api/src/routes.py
> +ongoing_proof_for_id = None
I don't think this will be needed

2021-02-23 23:57 UTC, ZackHolmberg commented on src/backend/services/mining-api/src/routes.py
> +    # TODO if proof for wrong id is received compare it with the current ongoing proof
Shouldn't be possible for a miner to send a proof for the wrong transaction as we will only have 1 mining session going at a time, and that mining will end server-side and client-side before another one begins

2021-02-24 00:24 UTC, ZackHolmberg commented on src/backend/.gitignore
> +**/__pycache__/
```
**/**.pyc
tests/**.pyc
.pytest_cache
__init__.pyc
```

Add that to this file and then we don't have to have it in any of the service-level gitingores

2021-02-25 05:03 UTC, ZackHolmberg approved these changes

2021-02-25 05:04 UTC, akshaysharma21 approved these changes

2021-02-25 05:04 UTC, merged