53: Create account page
ZackHolmberg/COMP4350-Project pull request #94
Opened 2021-03-06 09:52 UTC by ZackHolmberg

closes #53

2021-03-06 19:34 UTC, madisonfines requested changes

2021-03-06 19:34 UTC, madisonfines commented on src/backend/services/users-api/src/app/routes.py
> +        return jsonify(error=FailureReturnString.DATABASE_VERIFICATION_FAILURE.value, erroror=str(e)), HttpCode.BAD_REQUEST.value
Small spelling "error"!

2021-03-06 19:34 UTC, madisonfines commented on src/backend/services/users-api/src/app/routes.py
> +        return jsonify(error=FailureReturnString.DATABASE_VERIFICATION_FAILURE.value, erroror=str(e)), HttpCode.BAD_REQUEST.value
Same here!

2021-03-06 19:34 UTC, madisonfines commented on src/frontend/src/components/Button.vue
> +  computed: {
Can probably move this to export default class then mark it as "get"!

2021-03-06 19:34 UTC, madisonfines commented on src/frontend/src/components/Button.vue
> +  margin-left: 25%;
Move this to style.scss please :)

2021-03-06 19:34 UTC, madisonfines commented on src/frontend/src/pages/CreateAccountPage.vue
> +      width="300px"
You can move width and height to css by making this image have a class name. Also, I believe the login page has the same size logo so just use those variables from style for reuse!

2021-03-06 19:34 UTC, madisonfines commented on src/frontend/src/pages/CreateAccountPage.vue
> +.home {
Change this class name to create-account please!

2021-03-06 19:34 UTC, madisonfines commented on src/frontend/src/pages/CreateAccountPage.vue
> +.login-button {
Change this name to create account button so it doesn't clash with the login-button class in a different component. Also please move margins to style.scss!

2021-03-06 19:34 UTC, madisonfines commented on src/frontend/src/pages/CreateAccountPage.vue
> +body {
You don't need this body section! Background gets set in App.vue

2021-03-06 19:34 UTC, madisonfines commented on src/frontend/src/pages/CreateAccountPage.vue
> +img {
Please add relevant class names for img! When you use them like this it effects all images in the entire app so you wanna choose a specific class name

2021-03-06 19:34 UTC, madisonfines commented on src/frontend/src/pages/LoginPage.vue
> +    <router-link to="/createAccount" id="create-account-link" tag="a"
Add class name to router-link so colour of link can be changed through class!

2021-03-06 19:34 UTC, madisonfines commented on src/frontend/src/pages/CreateAccountPage.vue
> +a {
Don't need this link class!

2021-03-06 19:34 UTC, madisonfines commented on src/frontend/src/pages/LoginPage.vue
> +  methods: {
Can move this method inside export default class

2021-03-06 19:34 UTC, madisonfines commented on src/frontend/src/pages/NewTransactionPage.vue
> +
Can remove this line!

2021-03-06 19:34 UTC, madisonfines commented on src/frontend/tests/e2e/specs/testCreateAccount.js
> +describe("After loading the app", () => {
We should also be testing all the different toast messages the user can receive!

2021-03-06 19:34 UTC, madisonfines commented on src/frontend/tests/e2e/specs/testWallet.js
> +describe("On the homepage", () => {
Same here! Check wallet related toast messages

2021-03-07 02:45 UTC, madisonfines approved these changes
One small comment, but looks good to me!

![dwight](https://user-images.githubusercontent.com/77855966/110227329-b9239380-7ebc-11eb-8265-e500cd0c2432.jpg)

2021-03-07 02:45 UTC, madisonfines commented on src/frontend/src/pages/CreateAccountPage.vue
> +.login-logo {
I don't even think you need this here, I believe if you make the logo's class login-logo it'll reference all the info from the LoginPage!

2021-03-07 02:53 UTC, abhisachdev17 approved these changes
Looks good to me!

2021-03-07 02:53 UTC, merged